name: Test Action Netlify Deploy in preview mode

on:
  - push
  - pull_request
  - workflow_dispatch

defaults:
  run:
    working-directory: ./examples/gatsby-starter-default

jobs:
  test_deploy_gatsbyjs_yarn:
    name: Test Deploy GatsbyJS site to Netlify managed by pnpm
    runs-on: ubuntu-latest

    steps:
      - name: deploy to preview mode
        uses: ./
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          deploy_dir: ./public
          cache_path: |
            .cache
            public
            node_modules
